# Generated by Django 4.2.16 on 2024-09-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('is_published', models.BooleanField(default=False, help_text='Este campo prescisará estar marcado para a página ser exibida publicamente')),
                ('content', models.TextField()),
            ],
        ),
    ]
