# Generated by Django 4.2.16 on 2024-10-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='O HTML apenas será salvo dentro do campo code view'),
        ),
    ]
